<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateSettings</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlpbmNsdWRlZFBhY2thZ2VzID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJpbmNsdWRlZFBhY2thZ2VzIiApOw0KU3RyaW5nCWthZmthQm9vdHN0cmFwVXJsID0gSURhdGFV
dGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJrYWZrYUJvb3RzdHJhcFVybCIgKTsNClN0
cmluZwlrYWZrYVRvcGljTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAia2Fma2FUb3BpY05hbWUiICk7DQpTdHJpbmcJZXh0ZXJuYWxIb3N0bmFtZSAgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImV4dGVybmFsSG9zdG5hbWUiICk7DQoNCnRy
eSB7DQoJU2t5UHJvZmlsZXJNYW5hZ2VyLmdldEluc3RhbmNlKCkudXBkYXRlQ29uZmlnKGluY2x1
ZGVkUGFja2FnZXMsIGthZmthQm9vdHN0cmFwVXJsLCBrYWZrYVRvcGljTmFtZSwgZXh0ZXJuYWxI
b3N0bmFtZSk7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJtZXNzYWdlIiwgIkNv
bmZpZ3VyYXRpb24gc2F2ZWQgc3VjY2Vzc2Z1bGx5LiIpOw0KfSBjYXRjaChFeGNlcHRpb24gZXgp
IHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRmFpbGVkIHRvIHVwZGF0ZSB0aGUgY29u
ZmlndXJhdGlvbi4iKTsNCn0NCg0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
